CREATE TABLE greeting (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    hello VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'hello',
    world VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'world',
    status TINYINT(4) UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
